In [ ]:
import numpy as np 
'gbgbgb'

In [6]:
a = np.array([1, 2, 3, 4])
b = np.array([[1, 2, 3],
              [4, 5, 6]])

In [7]:
x = np.arange(10)

In [8]:
print(x[2:7])
print(x[:5])

[2 3 4 5 6]
[0 1 2 3 4]


In [9]:
x = np.arange(6).reshape(2, 3)
x.shape, x.dtype

((2, 3), dtype('int64'))

In [10]:
x[0, 1], x[:, 0]

(np.int64(1), array([0, 3]))

In [11]:
x + 10, x * 2

(array([[10, 11, 12],
        [13, 14, 15]]),
 array([[ 0,  2,  4],
        [ 6,  8, 10]]))

In [12]:
x.mean(), x.sum(), x.min(), x.max()

(np.float64(2.5), np.int64(15), np.int64(0), np.int64(5))